version: "3"
services:
    frontend:
        container_name: domain_checker
        build:
            context: ./client
            dockerfile: Dockerfile
        image: smartclick/domain_checker
        ports:
            - "3000:3000"
        volumes:
            - ./client:/usr/src/app
    backend:
        container_name: domain_checker
        build:
            context: ./server
            dockerfile: Dockerfile
        image: smartclick/domain_checker
        ports:
            - "5000:5000"
        volumes:
            - ./server:/usr/src/app